module.exports = {

  // Headers
  COMPANY_USER_ID: 'x-company-user-id',
  COMPANY_REQUEST_ID: 'x-compaby-request-id',

  // Cassandra
  CASSANDRA_URL: 'CASSANDRA_URL',
  CASSANDRA_PORT: 'CASSANDRA_PORT',
  CASSANDRA_USERNAME: 'CASSANDRA_USERNAME',
  CASSANDRA_PASSWORD: 'CASSANDRA_PASSWORD',
  CASSANDRA_KEYSPACE: 'CASSANDRA_KEYSPACE',

  // Errors
  GENERAL_ERROR: 'GENERAL_ERROR',
  INVALID_IP_ADDRESS: 'INVALID_IP_ADDRESS',
  EMAIL_ADDRESS_ALREADY_EXISTS: 'EMAIL_ADDRESS_ALREADY_EXISTS',
  USER_ID_IS_MISSING: 'USER_ID_IS_MISSING',
  ADDRESS_ID_IS_MISSING: 'ADDRESS_ID_IS_MISSING',
  IS_NOT_UUID: 'IS_NOT_UUID',
  IS_NOT_TIMESTAMP: 'IS_NOT_TIMESTAMP',

  // Date-time fields
  CREATED_DATE: 'created_date',
  UPDATED_DATE: 'updated_date',
  DATE_TERMS_ACCEPTED: 'date_terms_accepted',
  ADDRESS_CREATED: 'address_created',
  ADDRESS_UPDATED: 'address_updated',
};
